"""
Q17 · **수렴 · 오차예산** 게이트 (82차에 Mode B 두 축 등재).

계약 §1 "남는 것" 을 전부 숫자로.  ★ 축마다 성격이 다르다 — 그 차이를 뭉개지 않는다:
  · 대수 차수를 갖는 축: time 4, splitting 2, radial ≥6, **Q5b 공변 꺾임 2.45**
  · 지수 (스펙트럴) 축: angular, **Mode B 일관성**, **Mode B 반경 정의역**
  · 오차가 아니라 **정확**인 축: 충돌 3항
"""
import numpy as np
import pytest

pytest.importorskip("bianchi_rustcore")

from bianchi.q import contract as C  # noqa: E402


def test_discretization_axes_registered():
    """★ Mode B 두 축이 계약에 등재되어 있다 (82차)."""
    d = C.DISCRETIZATION
    assert "modeb_angular" in d and "modeb_range" in d
    for k in ("modeb_angular", "modeb_range"):
        assert d[k]["order"] == "spectral"
        assert d[k]["decay_rate"] > 0.3, k
    # 대수 축은 여전히 Q5b 꺾임 하나뿐
    assert d["angular"]["order_kinked"] == 2.45


def test_modeb_angular_axis_is_exponential_not_algebraic():
    """★★ 지수 수렴 실측 — 겉보기 '차수' 가 n 과 함께 **증가**한다."""
    from scripts.q17_convergence import _exp_rate, _modeb_err
    ns = [8, 12, 16, 24]
    errs = [_modeb_err(n) for n in ns]
    assert errs[0] > errs[-1] * 1e4, errs
    # 겉보기 대수차수가 단조 증가 = 지수 수렴의 서명
    ords = [np.log(errs[i] / errs[i + 1]) / np.log(ns[i + 1] / ns[i])
            for i in range(len(ns) - 1)]
    assert ords[-1] > ords[0] + 2.0, ords
    rate = _exp_rate(errs, ns)
    want = C.DISCRETIZATION["modeb_angular"]["decay_rate"]
    assert abs(rate - want) / want <= 0.25, (rate, want)


def test_modeb_range_axis_is_domain_truncation():
    """★ 반경 축은 **해상도**가 아니라 **정의역 폭**이다 (81차 분리의 등재)."""
    from scripts.q17_convergence import _modeb_err
    same = [_modeb_err(12, n_p) for n_p in (100, 400)]
    assert abs(same[0] - same[1]) / same[0] < 0.05, same     # 해상도 무관
    wide = [_modeb_err(12, 150, -6.0, 3.0), _modeb_err(12, 200, -8.0, 5.0)]
    assert wide[0] > 100.0 * wide[1], wide                   # 폭에 지수 민감


def test_budget_file_is_autogenerated_and_current():
    """★ 표는 자동 생성이어야 한다 (수기 금지) — 파일이 새 축을 담고 있다."""
    import pathlib
    txt = pathlib.Path("docs/Q-ERROR-BUDGET.md").read_text()
    assert "modeB angular" in txt and "modeB radial range" in txt
    assert "감쇠율" in txt
    assert "자동 생성" in txt
