from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import hashlib
import json
from typing import Mapping
import subprocess

import numpy as np
import sympy as sp
from sympy.printing import rust_code

GENERATOR_VERSION = "1.0.0"


@dataclass(frozen=True)
class GeneratedBundle:
    output_dir: Path
    files: tuple[str, ...]
    bundle_content_sha256: str


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_file(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def _fmt_float(x: float) -> str:
    return format(float(x), ".17g")


def _typeii_symbolics():
    sigma_p, sigma_m, sigma_13, n1, v2, gamma = sp.symbols(
        "sigma_p sigma_m sigma_13 n1 v2 gamma", real=True
    )
    sqrt3 = sp.sqrt(3)
    sigma2 = sigma_p**2 + sigma_m**2 + sigma_13**2
    omega = 1 - sigma2 - n1**2 / sp.Integer(12)
    gp = 1 + (gamma - 1) * v2**2
    gm = 1 - (gamma - 1) * v2**2
    sig2 = sigma_p + sqrt3 * sigma_m
    q = 2 * sigma2 + sp.Rational(1, 2) * (
        (3 * gamma - 2) + (2 - gamma) * v2**2
    ) * omega / gp
    ttil = (
        (3 * gamma - 4) * (1 - v2**2)
        + (2 - gamma) * sig2 * v2**2
    ) / gm
    rhs = sp.Matrix(
        [
            -(2 - q) * sigma_p
            + n1**2 / 3
            + gamma * omega * v2**2 / (2 * gp)
            - 3 * sigma_13**2,
            -(2 - q) * sigma_m
            + sqrt3 * gamma * omega * v2**2 / (2 * gp)
            + sqrt3 * sigma_13**2,
            sigma_13 * (-(2 - q) + 3 * sigma_p - sqrt3 * sigma_m),
            (q - 4 * sigma_p) * n1,
            v2 * (ttil - sig2),
        ]
    )
    state = [sigma_p, sigma_m, sigma_13, n1, v2]
    direction = sp.symbols("d_sigma_p d_sigma_m d_sigma_13 d_n1 d_v2", real=True)
    jvp = sp.simplify(rhs.jacobian(state) * sp.Matrix(direction))
    return state, gamma, direction, rhs, jvp


def _emit_cse_block(exprs, prefix: str = "t") -> tuple[list[str], list[str]]:
    symbols = sp.numbered_symbols(prefix)
    replacements, reduced = sp.cse(list(exprs), symbols=symbols, optimizations="basic")
    lets = [f"    let {sym}: f64 = {rust_code(sp.expand_mul(sp.N(expr, 17)))};" for sym, expr in replacements]
    outs = [rust_code(sp.expand_mul(sp.N(expr, 17))) for expr in reduced]
    return lets, outs


def _background_rs(formula_hash: str) -> str:
    state, gamma, direction, rhs, jvp = _typeii_symbolics()
    rhs_lets, rhs_out = _emit_cse_block(rhs, "r")
    jvp_lets, jvp_out = _emit_cse_block(jvp, "j")

    sample = {
        state[0]: sp.Rational(1, 4),
        state[1]: sp.Rational(1, 20),
        state[2]: sp.Rational(1, 30),
        state[3]: sp.Rational(4, 5),
        state[4]: sp.Rational(1, 20),
        gamma: sp.Rational(13, 10),
    }
    dsample = [2, -3, 5, 7, -11]
    rhs_expected = [float(sp.N(x.subs(sample), 18)) for x in rhs]
    jvp_expected = [
        float(sp.N(x.subs(sample).subs(dict(zip(direction, dsample))), 18))
        for x in jvp
    ]

    return f'''//! AUTO-GENERATED by BASS G-SYMBOLIC-LOWERING-II. DO NOT EDIT BY HAND.\n//! Formula authority SHA-256: {formula_hash}\n\npub const FORMULA_AUTHORITY_SHA256: &str = "{formula_hash}";\n\n#[inline]\npub fn rhs(state: &[f64; 5], gamma: f64) -> [f64; 5] {{\n    let sigma_p = state[0];\n    let sigma_m = state[1];\n    let sigma_13 = state[2];\n    let n1 = state[3];\n    let v2 = state[4];\n{chr(10).join(rhs_lets)}\n    [{', '.join(rhs_out)}]\n}}\n\n#[inline]\npub fn jvp(state: &[f64; 5], gamma: f64, direction: &[f64; 5]) -> [f64; 5] {{\n    let sigma_p = state[0];\n    let sigma_m = state[1];\n    let sigma_13 = state[2];\n    let n1 = state[3];\n    let v2 = state[4];\n    let d_sigma_p = direction[0];\n    let d_sigma_m = direction[1];\n    let d_sigma_13 = direction[2];\n    let d_n1 = direction[3];\n    let d_v2 = direction[4];\n{chr(10).join(jvp_lets)}\n    [{', '.join(jvp_out)}]\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    fn max_abs(a: &[f64], b: &[f64]) -> f64 {{\n        a.iter().zip(b).map(|(x,y)| (x-y).abs()).fold(0.0, f64::max)\n    }}\n\n    #[test]\n    fn generated_rhs_matches_sympy_receipt() {{\n        let state = [0.25, 0.05, 1.0/30.0, 0.8, 0.05];\n        let got = rhs(&state, 1.3);\n        let expected = [{', '.join(_fmt_float(x) for x in rhs_expected)}];\n        assert!(max_abs(&got, &expected) < 2e-13, "got={{got:?}} expected={{expected:?}}");\n    }}\n\n    #[test]\n    fn generated_jvp_matches_wolfram_sympy_receipt() {{\n        let state = [0.25, 0.05, 1.0/30.0, 0.8, 0.05];\n        let direction = [2.0, -3.0, 5.0, 7.0, -11.0];\n        let got = jvp(&state, 1.3, &direction);\n        let expected = [{', '.join(_fmt_float(x) for x in jvp_expected)}];\n        assert!(max_abs(&got, &expected) < 5e-12, "got={{got:?}} expected={{expected:?}}");\n    }}\n}}\n'''


def _kato_rs(formula_hash: str) -> str:
    return f'''//! AUTO-GENERATED low-rank moving-equilibrium action.\n//! Formula authority SHA-256: {formula_hash}\n\n#[derive(Clone, Debug)]\npub struct ProjectorFactors {{\n    pub r: Vec<f64>,\n    pub a: Vec<f64>,\n    pub rv: Vec<f64>,\n    pub av: Vec<f64>,\n    pub denominator: f64,\n    pub denominator_v: f64,\n}}\n\nfn validate(directions: &[[f64; 3]], weights: &[f64], y: &[f64], axis: usize) {{\n    assert_eq!(directions.len(), weights.len());\n    assert_eq!(directions.len(), y.len());\n    assert!(axis < 3);\n}}\n\npub fn projector_factors(directions: &[[f64; 3]], weights: &[f64], v: f64, axis: usize) -> ProjectorFactors {{\n    assert_eq!(directions.len(), weights.len());\n    assert!(axis < 3);\n    assert!(v.abs() < 1.0);\n    let gamma = 1.0 / (1.0 - v*v).sqrt();\n    let mut r = Vec::with_capacity(directions.len());\n    let mut a = Vec::with_capacity(directions.len());\n    let mut rv = Vec::with_capacity(directions.len());\n    let mut av = Vec::with_capacity(directions.len());\n    for (e, &w) in directions.iter().zip(weights) {{\n        let mu = e[axis];\n        let q = 1.0 - v*mu;\n        let d = gamma*q;\n        let ri = d.powi(-4);\n        let ai = w*q/(4.0*std::f64::consts::PI);\n        let rvi = 4.0*ri*(mu/q - gamma*gamma*v);\n        let avi = -w*mu/(4.0*std::f64::consts::PI);\n        r.push(ri); a.push(ai); rv.push(rvi); av.push(avi);\n    }}\n    let denominator: f64 = a.iter().zip(&r).map(|(x,y)| x*y).sum();\n    let denominator_v: f64 = av.iter().zip(&r).map(|(x,y)| x*y).sum::<f64>()\n        + a.iter().zip(&rv).map(|(x,y)| x*y).sum::<f64>();\n    ProjectorFactors {{ r, a, rv, av, denominator, denominator_v }}\n}}\n\npub fn projector_apply(directions: &[[f64; 3]], weights: &[f64], v: f64, axis: usize, y: &[f64]) -> Vec<f64> {{\n    validate(directions, weights, y, axis);\n    let f = projector_factors(directions, weights, v, axis);\n    let s: f64 = f.a.iter().zip(y).map(|(x,z)| x*z).sum();\n    f.r.iter().map(|ri| ri*s/f.denominator).collect()\n}}\n\npub fn projector_dv_apply(directions: &[[f64; 3]], weights: &[f64], v: f64, axis: usize, y: &[f64]) -> Vec<f64> {{\n    validate(directions, weights, y, axis);\n    let f = projector_factors(directions, weights, v, axis);\n    let s: f64 = f.a.iter().zip(y).map(|(x,z)| x*z).sum();\n    let sv: f64 = f.av.iter().zip(y).map(|(x,z)| x*z).sum();\n    f.r.iter().zip(&f.rv).map(|(ri,rvi)|\n        rvi*s/f.denominator + ri*sv/f.denominator - ri*s*f.denominator_v/(f.denominator*f.denominator)\n    ).collect()\n}}\n\npub fn kato_apply(directions: &[[f64; 3]], weights: &[f64], v: f64, vdot: f64, axis: usize, y: &[f64]) -> Vec<f64> {{\n    // K y = [Pdot,P]y = vdot * (Pv(P y) - P(Pv y)).\n    let py = projector_apply(directions, weights, v, axis, y);\n    let pv_py = projector_dv_apply(directions, weights, v, axis, &py);\n    let pv_y = projector_dv_apply(directions, weights, v, axis, y);\n    let p_pv_y = projector_apply(directions, weights, v, axis, &pv_y);\n    pv_py.iter().zip(p_pv_y).map(|(x,z)| vdot*(x-z)).collect()\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n    fn grid() -> ([[f64;3];6],[f64;6]) {{\n        ([[1.,0.,0.],[-1.,0.,0.],[0.,1.,0.],[0.,-1.,0.],[0.,0.,1.],[0.,0.,-1.]], [4.0*std::f64::consts::PI/6.0; 6])\n    }}\n    fn max_abs(v: &[f64]) -> f64 {{ v.iter().map(|x|x.abs()).fold(0.0,f64::max) }}\n\n    #[test]\n    fn projector_is_idempotent() {{\n        let (e,w)=grid(); let y=[0.2,-0.1,0.4,0.7,-0.3,0.9];\n        let p=projector_apply(&e,&w,0.05,1,&y);\n        let pp=projector_apply(&e,&w,0.05,1,&p);\n        let d:Vec<_>=pp.iter().zip(p).map(|(x,z)|x-z).collect();\n        assert!(max_abs(&d)<2e-14);\n    }}\n\n    #[test]\n    fn kato_commutator_identity_holds_as_action() {{\n        let (e,w)=grid(); let y=[0.2,-0.1,0.4,0.7,-0.3,0.9]; let v=0.05; let vd=0.03;\n        let py=projector_apply(&e,&w,v,1,&y);\n        let kpy=kato_apply(&e,&w,v,vd,1,&py);\n        let ky=kato_apply(&e,&w,v,vd,1,&y);\n        let pky=projector_apply(&e,&w,v,1,&ky);\n        let pd:Vec<_>=projector_dv_apply(&e,&w,v,1,&y).into_iter().map(|x|vd*x).collect();\n        let diff:Vec<_>=kpy.iter().zip(pky).zip(pd).map(|((a,b),c)|a-b-c).collect();\n        assert!(max_abs(&diff)<3e-13);\n    }}\n}}\n'''


def _dense_collision_reference(directions, weights, v, axis, y):
    e = np.asarray(directions, dtype=float)
    w = np.asarray(weights, dtype=float)
    y = np.asarray(y, dtype=float)
    vvec = np.zeros(3); vvec[axis] = v
    v2 = float(v*v)
    gamma = 1.0/np.sqrt(1-v2)
    mu = e[:,axis]
    D = gamma*(1-v*mu)
    ep = np.empty_like(e)
    if abs(v) < 1e-15:
        ep[:] = e
    else:
        ve = v*mu
        coeff = ((gamma-1.0)*ve/v2 - gamma)
        ep = (e + coeff[:,None]*vvec[None,:]) / D[:,None]
    wr = w/D**2
    gp = D**4*y
    cc = ep@ep.T
    K = (3/(16*np.pi))*(1+cc**2)*wr[None,:]
    return (1-v*mu)*D**-4*((K-np.eye(len(e)))@gp)


def _collision_rs(formula_hash: str) -> str:
    e = np.array([[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]],float)
    w = np.full(6,4*np.pi/6)
    y = np.array([1.0,.7,1.2,.9,.6,1.4])
    expected = _dense_collision_reference(e,w,.1,1,y)
    exp = ', '.join(_fmt_float(x) for x in expected)
    return f'''//! AUTO-GENERATED matrix-free scalar finite-tilt Thomson generator action.\n//! Formula authority SHA-256: {formula_hash}\n\nfn aberrate(e: [f64;3], v: f64, axis: usize) -> ([f64;3], f64) {{\n    assert!(axis < 3); assert!(v.abs() < 1.0);\n    if v.abs() < 1e-15 {{ return (e, 1.0); }}\n    let gamma = 1.0/(1.0-v*v).sqrt();\n    let mu = e[axis];\n    let ve = v*mu;\n    let d = gamma*(1.0-ve);\n    let coeff = (gamma-1.0)*ve/(v*v) - gamma;\n    let mut ep=e;\n    ep[axis] += coeff*v;\n    for x in &mut ep {{ *x /= d; }}\n    (ep,d)\n}}\n\npub fn collision_generator_apply(directions: &[[f64;3]], weights: &[f64], v: f64, axis: usize, y: &[f64]) -> Vec<f64> {{\n    // Moment-factorized rest-frame Thomson gain: I0 + e^a e^b M_ab.\n    assert_eq!(directions.len(),weights.len()); assert_eq!(directions.len(),y.len());\n    let n=directions.len();\n    let mut ep=Vec::with_capacity(n); let mut d=Vec::with_capacity(n);\n    let mut gp=Vec::with_capacity(n); let mut wr=Vec::with_capacity(n);\n    for i in 0..n {{\n        let (ei,di)=aberrate(directions[i],v,axis);\n        ep.push(ei); d.push(di); gp.push(di.powi(4)*y[i]); wr.push(weights[i]/di.powi(2));\n    }}\n    let mut i0=0.0; let mut moment=[[0.0_f64;3];3];\n    for i in 0..n {{\n        let wg=wr[i]*gp[i]; i0 += wg;\n        for a in 0..3 {{ for b in 0..3 {{ moment[a][b] += wg*ep[i][a]*ep[i][b]; }} }}\n    }}\n    let gamma=1.0/(1.0-v*v).sqrt();\n    let pref=3.0/(16.0*std::f64::consts::PI);\n    let mut out=vec![0.0;n];\n    for i in 0..n {{\n        let mut quad=0.0;\n        for a in 0..3 {{ for b in 0..3 {{ quad += ep[i][a]*moment[a][b]*ep[i][b]; }} }}\n        let gain=pref*(i0+quad);\n        let qout=1.0-v*directions[i][axis];\n        out[i]=qout*d[i].powi(-4)*(gain-gp[i]);\n        debug_assert!((d[i]-gamma*qout).abs()<1e-12);\n    }}\n    out\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n    fn grid() -> ([[f64;3];6],[f64;6]) {{ ([[1.,0.,0.],[-1.,0.,0.],[0.,1.,0.],[0.,-1.,0.],[0.,0.,1.],[0.,0.,-1.]], [4.0*std::f64::consts::PI/6.0;6]) }}\n    #[test]\n    fn finite_tilt_action_matches_independent_dense_python_receipt() {{\n        let (e,w)=grid(); let y=[1.0,0.7,1.2,0.9,0.6,1.4];\n        let got=collision_generator_apply(&e,&w,0.1,1,&y);\n        let expected=[{exp}];\n        let err=got.iter().zip(expected).map(|(a,b)|(a-b).abs()).fold(0.0,f64::max);\n        assert!(err<3e-13,"err={{err}} got={{got:?}}");\n    }}\n    #[test]\n    fn rest_isotropic_state_is_null() {{\n        let (e,w)=grid(); let y=[1.0;6];\n        let got=collision_generator_apply(&e,&w,0.0,1,&y);\n        assert!(got.iter().map(|x|x.abs()).fold(0.0,f64::max)<3e-15);\n    }}\n}}\n'''


def generate_typeii_rust_bundle(
    output_dir: str | Path,
    *,
    formula_authority_hash: str,
    provenance_hashes: Mapping[str, str] | None = None,
    rustfmt_path: str | Path | None = None,
    rustfmt_version: str | None = None,
) -> GeneratedBundle:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    provenance_hashes = dict(sorted((provenance_hashes or {}).items()))

    contents = {
        "typeii_background.rs": _background_rs(formula_authority_hash),
        "typeii_kato.rs": _kato_rs(formula_authority_hash),
        "typeii_collision.rs": _collision_rs(formula_authority_hash),
        "mod.rs": "pub mod typeii_background;\npub mod typeii_kato;\npub mod typeii_collision;\n",
    }
    for name, text in contents.items():
        (out / name).write_text(text)

    formatter = None
    if rustfmt_path is not None:
        rustfmt_path = str(rustfmt_path)
        rs_files = [str(out / name) for name in sorted(contents) if name.endswith(".rs")]
        subprocess.run([rustfmt_path, "--edition", "2021", *rs_files], check=True)
        formatter = {"tool": "rustfmt", "version": rustfmt_version or "UNRECORDED"}

    file_hashes = {name: _sha256_file(out / name) for name in sorted(contents)}
    bundle_hash_input = json.dumps(file_hashes, sort_keys=True, separators=(",", ":")).encode()
    bundle_hash = _sha256_bytes(bundle_hash_input)
    manifest = {
        "schema": "bass-generated-rust-v1",
        "generator_version": GENERATOR_VERSION,
        "formula_authority_sha256": formula_authority_hash,
        "provenance_hashes": provenance_hashes,
        "generated_files": file_hashes,
        "bundle_content_sha256": bundle_hash,
        "formatter": formatter,
        "semantics": {
            "background": "exact Type-II aligned 5-state specialization",
            "projector": "low-rank scalar bolometric moving-equilibrium action",
            "kato": "matrix-free [Pdot,P] action",
            "collision": "matrix-free moment-factorized finite-tilt scalar Thomson generator action",
        },
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True))
    files = tuple(sorted([*contents.keys(), "manifest.json"]))
    return GeneratedBundle(out, files, bundle_hash)
