"""R4 off-axis m-resolved SAE control in an instantaneous body-fixed frame.

Scientific ceiling: one-active-electron frozen neutral-H control only.
No physical H- channel, no two-electron antisymmetrization, no TCS/DDCS promotion.

The target potential is split as exact nuclear Coulomb multipoles plus a smooth
neutral-H screening term.  For b>0, the instantaneous target axis is rotated to
+z.  The body Hamiltonian preserves m and is propagated independently by m
sector.  The changing frame is applied by exact finite rotations generated by
L_y, avoiding the coordinate stiffness theta_dot ~ v/b at small b.
"""
from __future__ import annotations
from dataclasses import dataclass
from functools import lru_cache
import math
import numpy as np
from scipy.constants import physical_constants
from scipy.linalg import eigh_tridiagonal
from scipy.special import sph_harm_y
from scipy.sparse import coo_matrix, diags, eye
from scipy.sparse.linalg import spsolve
from sympy.physics.wigner import wigner_3j

MP = physical_constants['proton-electron mass ratio'][0]
HA_EV = physical_constants['Hartree energy in eV'][0]
MU = MP/(MP+1.0)


def speed_au_from_keV(energy_keV: float) -> float:
    if energy_keV <= 0:
        raise ValueError('energy_keV must be positive')
    return math.sqrt(2.0*(energy_keV*1000.0/HA_EV)/(MP+1.0))


def stable_screening_potential(s):
    """V_scr(s)=1/s-exp(-2s)(1+1/s), with a cancellation-safe s->0 limit."""
    s = np.asarray(s, dtype=float)
    out = np.empty_like(s)
    mask = s > 1e-12
    sm = s[mask]
    out[mask] = -np.expm1(-2.0*sm)/sm - np.exp(-2.0*sm)
    # Series through s^4 is more than enough inside the tiny switch region.
    x = s[~mask]
    out[~mask] = 1.0 - (2.0/3.0)*x*x + (2.0/3.0)*x**3 - (2.0/5.0)*x**4
    return out.item() if out.ndim == 0 else out


def direct_neutral_potential(s):
    s=np.asarray(s,dtype=float)
    if np.any(s==0):
        raise ValueError('direct neutral potential singular at s=0')
    out=-np.exp(-2*s)*(1+1/s)
    return out.item() if out.ndim==0 else out


def radial_hamiltonian(nr: int, rmax: float, l: int, potential=None, mu: float=MU):
    if nr < 3 or rmax <= 0 or l < 0:
        raise ValueError('invalid radial basis')
    dr = rmax/(nr+1)
    r = dr*np.arange(1,nr+1)
    V = -1/r if potential is None else np.asarray(potential(r),float)
    diag = 1/(mu*dr*dr) + l*(l+1)/(2*mu*r*r) + V
    off = np.full(nr-1,-1/(2*mu*dr*dr))
    e,u=eigh_tridiagonal(diag,off)
    return r,diags([off,diag,off],[-1,0,1],format='csc'),e,u


@lru_cache(maxsize=None)
def gaunt_p_lambda(l: int, lp: int, m: int, lam: int) -> float:
    """Integral Y_lm^* P_lam Y_l'p over sphere; m'=m for axial potential."""
    if min(l,lp,lam) < 0 or abs(m)>l or abs(m)>lp:
        return 0.0
    if lam < abs(l-lp) or lam > l+lp or ((l+lam+lp)&1):
        return 0.0
    # P_lam = sqrt(4pi/(2lam+1)) Y_lam,0.
    val = ((-1)**m)*math.sqrt((2*l+1)*(2*lp+1))*float(
        wigner_3j(l,lam,lp,0,0,0)*wigner_3j(l,lam,lp,-m,0,m)
    )
    return val


@lru_cache(maxsize=None)
def _gl(nangle: int):
    if nangle < 8:
        raise ValueError('nangle too small')
    return np.polynomial.legendre.leggauss(nangle)


@lru_cache(maxsize=None)
def _axis_basis(lmax: int, m: int, nangle: int):
    if abs(m)>lmax:
        raise ValueError('|m| > lmax')
    mu,w=_gl(nangle)
    theta=np.arccos(mu)
    ls=np.arange(abs(m),lmax+1,dtype=int)
    # scipy 1.17 sph_harm_y(n,m,theta,phi). At phi=0 values are real up to roundoff.
    Y=np.array([sph_harm_y(int(l),int(m),theta,np.zeros_like(theta)) for l in ls],complex)
    return ls,mu,w,Y


def nuclear_axis_matrix(r, R: float, lmax: int, m: int, axis_sign: int=1):
    """Exact projected -1/|r-R zhat| matrix using Coulomb multipoles and 3j Gaunts."""
    r=np.asarray(r,float)
    if R < 0 or axis_sign not in (-1,1):
        raise ValueError('invalid R/axis_sign')
    ls=np.arange(abs(m),lmax+1,dtype=int); q=len(ls)
    out=np.zeros((len(r),q,q),float)
    for a,l in enumerate(ls):
        for b,lp in enumerate(ls):
            for lam in range(abs(int(l-lp)),int(l+lp)+1):
                g=gaunt_p_lambda(int(l),int(lp),int(m),lam)
                if g==0.0: continue
                if R==0.0:
                    radial = (1.0/r) if lam==0 else np.zeros_like(r)
                else:
                    rlo=np.minimum(r,R); rhi=np.maximum(r,R)
                    radial=(rlo**lam)/(rhi**(lam+1))
                out[:,a,b] -= (axis_sign**lam)*g*radial
    return out


def screening_axis_matrix(r, R: float, lmax: int, m: int, nangle: int=64, axis_sign: int=1):
    """Smooth screening matrix by 1D mu quadrature in the body/axial frame."""
    r=np.asarray(r,float)
    ls,mu,w,Y=_axis_basis(lmax,m,nangle)
    s=np.sqrt(np.maximum(0.0,r[:,None]**2+R*R-2*r[:,None]*R*axis_sign*mu[None,:]))
    V=stable_screening_potential(s)
    # phi integral gives 2pi and delta_m,m'.
    return (2*np.pi*np.einsum('ak,rk,bk,k->rab',Y.conj(),V,Y,w,optimize=True)).real


def axis_potential_matrix(r,R,lmax,m,nangle=64,axis_sign=1):
    return nuclear_axis_matrix(r,R,lmax,m,axis_sign)+screening_axis_matrix(r,R,lmax,m,nangle,axis_sign)


def direct_axis_matrix(r,R,lmax,m,nangle=256,axis_sign=1):
    r=np.asarray(r,float);ls,mu,w,Y=_axis_basis(lmax,m,nangle)
    s=np.sqrt(np.maximum(0.0,r[:,None]**2+R*R-2*r[:,None]*R*axis_sign*mu[None,:]))
    if np.any(s==0): raise ValueError('quadrature hit singular point')
    V=direct_neutral_potential(s)
    return (2*np.pi*np.einsum('ak,rk,bk,k->rab',Y.conj(),V,Y,w,optimize=True)).real


@dataclass(frozen=True)
class StateLayout:
    lmax: int
    states: tuple
    by_m: dict
    by_l: dict

    @staticmethod
    def build(lmax: int):
        states=[];by_m={m:[] for m in range(-lmax,lmax+1)};by_l={l:[] for l in range(lmax+1)}
        for l in range(lmax+1):
            for m in range(-l,l+1):
                idx=len(states);states.append((l,m));by_m[m].append(idx);by_l[l].append(idx)
        return StateLayout(lmax,tuple(states),{k:tuple(v) for k,v in by_m.items()},{k:tuple(v) for k,v in by_l.items()})

    @property
    def size(self): return len(self.states)


@lru_cache(maxsize=None)
def ly_matrix(l: int):
    ms=np.arange(-l,l+1); n=2*l+1
    Lp=np.zeros((n,n),complex)
    for j,m in enumerate(ms[:-1]):
        Lp[j+1,j]=math.sqrt(l*(l+1)-m*(m+1))
    Lm=Lp.conj().T
    return (Lp-Lm)/(2j)


@lru_cache(maxsize=None)
def ly_eigh(l: int):
    return np.linalg.eigh(ly_matrix(l))


def apply_y_rotation(psi_rs, layout: StateLayout, angle: float):
    if angle==0.0: return psi_rs.copy()
    out=psi_rs.copy()
    for l,idx in layout.by_l.items():
        vals,vecs=ly_eigh(l)
        R=(vecs*np.exp(1j*angle*vals))@vecs.conj().T
        out[:,idx]=out[:,idx]@R.T
    return out


def _build_h0_sector(nr,rmax,ls):
    q=len(ls);RR=[];CC=[];DD=[];r=None;levels={};vectors={}
    for a,l in enumerate(ls):
        r,H,e,u=radial_hamiltonian(nr,rmax,l); levels[l]=e;vectors[l]=u
        H=H.tocoo(); RR.extend(H.row*q+a); CC.extend(H.col*q+a); DD.extend(H.data)
    return r,coo_matrix((DD,(RR,CC)),shape=(nr*q,nr*q)).tocsc(),levels,vectors


def _local_sparse(W):
    nr,q,_=W.shape
    pr=np.repeat(np.arange(nr),q*q);ii=np.tile(np.repeat(np.arange(q),q),nr);jj=np.tile(np.tile(np.arange(q),q),nr)
    return coo_matrix((W.ravel(),(pr*q+ii,pr*q+jj)),shape=(nr*q,nr*q)).tocsc()


def _cayley(H,vec,dt):
    I=eye(H.shape[0],format='csc',dtype=complex)
    return spsolve(I+.5j*dt*H,(I-.5j*dt*H)@vec)


class BodySectorSystem:
    def __init__(self,nr=80,rmax=36.,lmax=4,nangle=48):
        self.nr=nr;self.rmax=rmax;self.lmax=lmax;self.nangle=nangle;self.layout=StateLayout.build(lmax)
        self.sectors={};self.r=None;self.levels={};self.vectors={}
        for m in range(-lmax,lmax+1):
            ls=tuple(range(abs(m),lmax+1))
            r,H0,lev,vec=_build_h0_sector(nr,rmax,ls)
            if self.r is None:self.r=r
            self.sectors[m]=(ls,H0)
            self.levels.update({(l,m):lev[l] for l in ls})
            self.vectors.update({(l,m):vec[l] for l in ls})

    def body_cayley(self,psi_rs,R,dt,axis_sign=1):
        out=psi_rs.copy()
        for m,(ls,H0) in self.sectors.items():
            idx=self.layout.by_m[m]; q=len(idx)
            W=axis_potential_matrix(self.r,R,self.lmax,m,self.nangle,axis_sign)
            H=H0+_local_sparse(W)
            vec=out[:,idx].reshape(self.nr*q)
            out[:,idx]=_cayley(H,vec,dt).reshape(self.nr,q)
        return out

    def initial_projectile_1s(self):
        psi=np.zeros((self.nr,self.layout.size),complex)
        idx=self.layout.states.index((0,0))
        psi[:,idx]=self.vectors[(0,0)][:,0]
        return psi

    def projectile_bound_probability(self,psi):
        p=0.0
        for idx,(l,m) in enumerate(self.layout.states):
            e=self.levels[(l,m)];u=self.vectors[(l,m)]
            c=u.T.conj()@psi[:,idx]
            p+=float(np.sum(np.abs(c[e<0])**2))
        return p


def run_axial_mresolved(nr=80,rmax=36.,lmax=4,dt=.1,zmax=8.,energy_keV=100.,nangle=48):
    sys=BodySectorSystem(nr,rmax,lmax,nangle); psi=sys.initial_projectile_1s(); initial=psi.copy()
    v=speed_au_from_keV(energy_keV);steps=int(np.ceil(2*zmax/(v*dt)));h=2*zmax/(v*steps)
    maxnorm=0.0
    for j in range(steps):
        z=zmax-v*(j+.5)*h; R=abs(z); sign=1 if z>=0 else -1
        psi=sys.body_cayley(psi,R,h,sign)
        maxnorm=max(maxnorm,abs(float(np.vdot(psi,psi).real)-1))
    nonzero_m=0.0
    for idx,(l,m) in enumerate(sys.layout.states):
        if m!=0:nonzero_m+=float(np.sum(np.abs(psi[:,idx])**2))
    return dict(energy_keV=energy_keV,b_a0=0.0,nr=nr,rmax_a0=rmax,lmax=lmax,nangle=nangle,
                dt_requested_au=dt,dt_actual_au=h,zmax_a0=zmax,speed_au=v,steps=steps,
                norm=float(np.vdot(psi,psi).real),max_norm_drift=maxnorm,m_nonzero_probability=nonzero_m,
                projectile_bound_probability=sys.projectile_bound_probability(psi),production_enabled=False),dict(final_psi=psi,initial_psi=initial,r_a0=sys.r)


def run_offaxis(nr=80,rmax=36.,lmax=4,dt=.1,zmax=8.,energy_keV=100.,b=1.0,nangle=48):
    if b<=0: raise ValueError('use axial lane for b=0')
    sys=BodySectorSystem(nr,rmax,lmax,nangle);psi=sys.initial_projectile_1s();initial=psi.copy()
    v=speed_au_from_keV(energy_keV);steps=int(np.ceil(2*zmax/(v*dt)));h=2*zmax/(v*steps);maxnorm=0.0
    for j in range(steps):
        z0=zmax-v*j*h;z1=zmax-v*(j+1)*h;zm=.5*(z0+z1)
        th0=math.atan2(b,z0);th1=math.atan2(b,z1);dth=th1-th0
        psi=apply_y_rotation(psi,sys.layout,.5*dth)
        psi=sys.body_cayley(psi,math.hypot(b,zm),h,1)
        psi=apply_y_rotation(psi,sys.layout,.5*dth)
        maxnorm=max(maxnorm,abs(float(np.vdot(psi,psi).real)-1))
    return dict(energy_keV=energy_keV,b_a0=b,nr=nr,rmax_a0=rmax,lmax=lmax,nangle=nangle,
                dt_requested_au=dt,dt_actual_au=h,zmax_a0=zmax,speed_au=v,steps=steps,
                norm=float(np.vdot(psi,psi).real),max_norm_drift=maxnorm,
                projectile_bound_probability=sys.projectile_bound_probability(psi),
                finite_box_complement_diagnostic=1-sys.projectile_bound_probability(psi),
                complement_is_ionization=False,production_enabled=False),dict(final_psi_body=psi,initial_psi_body=initial,r_a0=sys.r)


def frozen_neutral_target_bound_spectrum(nr=800,rmax=80.,l=0):
    """Bound-spectrum diagnostic of the frozen one-electron neutral-H direct potential."""
    pot=lambda r:-np.exp(-2*r)*(1+1/r)
    r,H,e,u=radial_hamiltonian(nr,rmax,l,potential=pot,mu=1.0)
    return e[e<0],e[:8]

@lru_cache(maxsize=None)
def lz_matrix(l: int):
    return np.diag(np.arange(-l,l+1,dtype=float)).astype(complex)


def rotation_matrix_l(l: int, alpha: float, beta: float, gamma: float=0.0):
    """Active z-y-z rotation U=exp(-i alpha Lz) exp(-i beta Ly) exp(-i gamma Lz)."""
    ms=np.arange(-l,l+1,dtype=float)
    Uz1=np.diag(np.exp(-1j*alpha*ms)); Uz2=np.diag(np.exp(-1j*gamma*ms))
    vals,vecs=ly_eigh(l); Uy=(vecs*np.exp(-1j*beta*vals))@vecs.conj().T
    return Uz1@Uy@Uz2


def rotation_matrix_global(layout: StateLayout, alpha: float, beta: float, gamma: float=0.0):
    U=np.zeros((layout.size,layout.size),complex)
    for l,idx in layout.by_l.items():
        U[np.ix_(idx,idx)]=rotation_matrix_l(l,alpha,beta,gamma)
    return U


def axis_operator_global_at_r(r: float,R: float,lmax: int,nangle: int=96):
    layout=StateLayout.build(lmax);W=np.zeros((layout.size,layout.size),complex)
    for m,idx in layout.by_m.items():
        block=axis_potential_matrix(np.array([r]),R,lmax,m,nangle,1)[0]
        W[np.ix_(idx,idx)]=block
    return W


def direct_operator_global_at_r(r: float,R: float,theta_R: float,phi_R: float,lmax: int,nmu: int=48,nphi: int=96):
    """Independent full-sphere quadrature of the neutral-H potential matrix."""
    layout=StateLayout.build(lmax);mu,wmu=np.polynomial.legendre.leggauss(nmu);theta=np.arccos(mu)
    phi=2*np.pi*np.arange(nphi)/nphi;tt,pp=np.meshgrid(theta,phi,indexing='ij');mm,_=np.meshgrid(mu,phi,indexing='ij')
    dot=mm*np.cos(theta_R)+np.sqrt(np.maximum(0,1-mm*mm))*np.sin(theta_R)*np.cos(pp-phi_R)
    s=np.sqrt(r*r+R*R-2*r*R*dot)
    V=direct_neutral_potential(s).ravel();weights=(wmu[:,None]*np.full((1,nphi),2*np.pi/nphi)).ravel()
    Y=[]
    for l,m in layout.states:Y.append(sph_harm_y(l,m,tt,pp).ravel())
    Y=np.asarray(Y)
    return np.einsum('ak,k,bk,k->ab',Y.conj(),V,Y,weights,optimize=True)


def scalar_field_from_coeff(coeff,layout: StateLayout,theta,phi):
    out=np.zeros(np.broadcast(theta,phi).shape,complex)
    for c,(l,m) in zip(coeff,layout.states):out+=c*sph_harm_y(l,m,theta,phi)
    return out
